name: CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a sample command
        run: echo "CI is working!"
